### ISSUE TITLE
May I have your contact details？

### ISSUE THREAD

**Issue by Johnnyallen07** [seermer/HollowKnight_RL#5]
Sorry to bother you, I am very interested in RL related training, and I wanna apply it to train bosses instead of agent of player. Could I have some suggestions from you? btw, I can speak Mandarin, so we can talk on WeChat.

**Comment by seermer** [comment]
tbh I might be limited with what I can help with. But sure, please email me at mervynyang26@gmail.com (or send me your WeChat ID through email).
